# source (already created by flux bootstrap) ↓ just for clarity
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: homelab-k8s-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jamilshaikh07/homelab-k8s-gitops
  ref:
    branch: main
---
# kustomization → watches ./flux/apps/nginx
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  targetNamespace: webserver
  interval: 1m
  path: ./flux/apps/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-k8s-gitops
