apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nginx-dev

namePrefix: dev-

commonLabels:
  environment: development
  variant: dev

commonAnnotations:
  environment: "development"
  note: "This is the dev environment configuration"

patches:
  - path: patch.yaml

replicas:
  - name: nginx-deployment
    count: 1