apiVersion: v1
kind: Service
metadata:
  name: nginx-metrics
  labels:
    app: nginx
    component: metrics
spec:
  ports:
  - port: 9113
    targetPort: 9113
    protocol: TCP
    name: metrics
  selector:
    app: nginx
  type: ClusterIP
