apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nginx-qa

namePrefix: qa-

commonLabels:
  environment: qa
  variant: testing

commonAnnotations:
  environment: "qa"
  note: "This is the QA environment configuration"

patches:
  - path: patch.yaml

replicas:
  - name: nginx-deployment
    count: 2