apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: nginx-prod

namePrefix: prod-

commonLabels:
  environment: production
  variant: stable

commonAnnotations:
  environment: "production"
  note: "This is the production environment configuration"

patches:
  - path: patch.yaml

replicas:
  - name: nginx-deployment
    count: 3